# Site settings
title: "4pFoods - Whitelabel: Inova"
email: dev@ocupop.com
url: "http://inova.4pfoods.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics_code:

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder
